"""add_expires_at_to_camions_and_offres

Revision ID: f763da0c616a
Revises: 
Create Date: 2026-07-29 07:41:02.806078
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f763da0c616a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_camions_chauffeur_id'), 'camions', ['chauffeur_id'], unique=False)
    op.drop_index(op.f('idx_user_photos_user_id'), table_name='user_photos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_user_photos_user_id'), 'user_photos', ['user_id'], unique=False)
    op.drop_index(op.f('ix_camions_chauffeur_id'), table_name='camions')
    # ### end Alembic commands ###
